#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Qwen3.6 / vLLM 全面 API + Agent + Vision 测试脚本 v3
====================================================

版本: 2026-09-30-r4

本版重点
--------
1. 修复 Thinking OFF / ON 判定器。
2. Responses Vision 使用当前 OpenAPI 要求的:
      {"type":"input_image","detail":"auto","image_url":"data:image/..."}
3. Vision + Tool Calling 使用明确的 top_text 字段。
4. 增加网络/服务异常重试机制。
5. 默认读取超时提高到 900 秒，适配内网模型慢响应。
6. 只对“可能恢复”的错误自动重试：
   - 连接错误 / ConnectTimeout
   - 408 / 425 / 429 / 500 / 502 / 503 / 504
   - ReadTimeout 默认不自动重试，避免前一个重推理仍在服务端执行时重复压测；
     如确需重试可加 --retry-read-timeout。
7. SSE 仅在“尚未收到有效流数据”时自动重试；收到部分流后中断不会盲目重放。
8. 每条记录保存 attempts，能看出是否靠重试恢复。
9. Anthropic 出现 stop_reason=tool_use 但 content[] 无 tool_use 时明确判为协议结构不一致。

默认覆盖
--------
- /v1/models, /version, /metrics, /openapi.json
- /tokenize, /detokenize, /v1/messages/count_tokens
- OpenAI Chat:
  非流式 / SSE / Thinking OFF / Thinking ON / Tool Call / Tool Result Loop
- OpenAI Responses:
  非流式 / SSE / Function Call / Function Call Output Loop
- Anthropic Messages:
  非流式 / SSE / Tool Use / Tool Result Loop
- Vision:
  Chat Base64 单图 / SSE / 多图 / Vision+Tool
  Responses input_image
  Anthropic Base64 image
- 可选公网 image_url
- 可选长上下文

依赖
----
    pip install requests pillow

推荐 PowerShell
---------------
    python .\\qwen_api_training_test_v3.py `
      --base-url http://<INTERNAL_HOST>:<PORT> `
      --api-key xxx

默认参数
--------
    connect timeout : 15 s
    read timeout    : 900 s
    retries         : 2   （即最多 3 次尝试）
    retry backoff   : 15 s 指数退避
    inter-test delay: 2 s
    heavy cooldown  : 15 s

如果确认 ReadTimeout 也要自动重试：
    --retry-read-timeout

注意
----
ReadTimeout 与普通“网络连接失败”不同。模型请求已经送到服务端后，客户端超时并不意味着
服务端推理已经取消。自动再次提交可能造成两个重推理同时占用 NPU，所以默认不重试
ReadTimeout，而是把读取超时放宽到 900 秒。

输出
----
qwen_api_test_records_v3/<timestamp>/
  summary.md
  manifest.json
  environment.json
  openapi_paths.txt
  assets/*.png
  records/*.json
  streams/*.sse.txt
  long_context/*.txt
"""

from __future__ import annotations

import argparse
import base64
import hashlib
import json
import os
import platform
import re
import sys
import time
import traceback
from dataclasses import asdict, dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Callable, Optional

import requests
from PIL import Image, ImageDraw, ImageFont


SCRIPT_VERSION = "2026-09-30-r4"
# Public training-repo copy: example internal URL sanitized; test logic unchanged.
# Baseline 20260930_095033 was generated by local script SHA256:
# 106727cae3e73dd7f5947e439a68b1be88b2d79c41f62413e5baa6b05ecb303b
DEFAULT_MODEL = "qwen3.6"
DEFAULT_CONTEXT = 131072

DEFAULT_CONNECT_TIMEOUT = 15
DEFAULT_READ_TIMEOUT = 900
DEFAULT_RETRIES = 2
DEFAULT_RETRY_BACKOFF = 15.0
DEFAULT_MAX_BACKOFF = 120.0
DEFAULT_INTER_TEST_DELAY = 2.0
DEFAULT_HEAVY_COOLDOWN = 15.0

RETRYABLE_HTTP_STATUS = {408, 425, 429, 500, 502, 503, 504}


def now_iso() -> str:
    return datetime.now(timezone.utc).astimezone().isoformat(timespec="seconds")


def js(x: Any) -> str:
    return json.dumps(x, ensure_ascii=False, indent=2)


def script_sha256() -> str:
    try:
        return hashlib.sha256(Path(__file__).read_bytes()).hexdigest()
    except Exception:
        return "unknown"


def sha_bytes(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def sha_text(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def masked(secret: str) -> str:
    if not secret:
        return ""
    if len(secret) <= 8:
        return "***"
    return secret[:3] + "***" + secret[-3:]


def redact(obj: Any, secret: str) -> Any:
    """日志脱敏；大图片和长文本不重复落盘。"""
    if isinstance(obj, dict):
        out = {}
        for k, v in obj.items():
            if k == "data" and isinstance(v, str) and len(v) > 1000:
                try:
                    raw = base64.b64decode(v)
                    out[k] = (
                        f"<BASE64_IMAGE_OMITTED bytes={len(raw)} "
                        f"sha256={sha_bytes(raw)}>"
                    )
                except Exception:
                    out[k] = f"<LARGE_DATA_OMITTED chars={len(v)}>"
            else:
                out[k] = redact(v, secret)
        return out

    if isinstance(obj, list):
        return [redact(v, secret) for v in obj]

    if isinstance(obj, str):
        text = obj.replace(secret, masked(secret)) if secret else obj

        if text.startswith("data:image/") and ";base64," in text:
            head, b64 = text.split(";base64,", 1)
            try:
                raw = base64.b64decode(b64)
                return (
                    f"{head};base64,<OMITTED bytes={len(raw)} "
                    f"sha256={sha_bytes(raw)}>"
                )
            except Exception:
                return f"{head};base64,<OMITTED chars={len(b64)}>"

        if len(text) > 30000:
            return (
                f"<LONG_TEXT_OMITTED chars={len(text)} sha256={sha_text(text)}>\n"
                f"HEAD:\n{text[:600]}\n...\nTAIL:\n{text[-600:]}"
            )
        return text

    return obj


def get_font(size: int = 54) -> ImageFont.ImageFont:
    candidates = [
        "C:/Windows/Fonts/arial.ttf",
        "C:/Windows/Fonts/calibri.ttf",
        "C:/Windows/Fonts/segoeui.ttf",
        "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf",
        "/usr/share/fonts/truetype/liberation2/LiberationSans-Regular.ttf",
        "/System/Library/Fonts/Supplemental/Arial.ttf",
    ]
    for p in candidates:
        try:
            if Path(p).exists():
                return ImageFont.truetype(p, size=size)
        except Exception:
            pass
    try:
        return ImageFont.truetype("DejaVuSans.ttf", size=size)
    except Exception:
        return ImageFont.load_default()


def make_assets(out: Path) -> dict[str, dict[str, Any]]:
    out.mkdir(parents=True, exist_ok=True)
    f = get_font(54)
    small = get_font(30)

    # 图 1 Ground Truth:
    # AI TEST 2026 / 3 red circles / 2 blue squares / green triangle bottom-right
    img1 = Image.new("RGB", (1200, 800), "white")
    d = ImageDraw.Draw(img1)
    d.text((45, 35), "AI TEST 2026", fill="black", font=f)

    for box in [(120, 220, 300, 400), (390, 220, 570, 400), (660, 220, 840, 400)]:
        d.ellipse(box, fill=(230, 30, 30), outline="black", width=5)

    for box in [(135, 520, 295, 680), (405, 520, 565, 680)]:
        d.rectangle(box, fill=(30, 90, 230), outline="black", width=5)

    d.polygon(
        [(900, 685), (1130, 685), (1015, 465)],
        fill=(20, 175, 75),
        outline="black",
    )
    d.text((855, 720), "BOTTOM RIGHT", fill="black", font=small)

    p1 = out / "vision_test_1.png"
    img1.save(p1, "PNG")

    # 图 2 Ground Truth:
    # SECOND IMAGE / 4 purple squares / 1 orange circle
    img2 = Image.new("RGB", (1200, 800), "white")
    d2 = ImageDraw.Draw(img2)
    d2.text((45, 35), "SECOND IMAGE", fill="black", font=f)

    for i in range(4):
        x = 120 + i * 230
        d2.rectangle((x, 240, x + 150, 390), fill=(145, 60, 190), outline="black", width=5)

    d2.ellipse((470, 500, 730, 760), fill=(245, 145, 30), outline="black", width=5)

    p2 = out / "vision_test_2.png"
    img2.save(p2, "PNG")

    def pack(path: Path, truth: dict[str, Any]) -> dict[str, Any]:
        raw = path.read_bytes()
        return {
            "path": str(path),
            "filename": path.name,
            "bytes": len(raw),
            "sha256": sha_bytes(raw),
            "b64": base64.b64encode(raw).decode("ascii"),
            "truth": truth,
        }

    return {
        "image1": pack(
            p1,
            {
                "text": "AI TEST 2026",
                "red_circles": 3,
                "blue_squares": 2,
                "green_triangle_position": "bottom-right",
            },
        ),
        "image2": pack(
            p2,
            {
                "text": "SECOND IMAGE",
                "purple_squares": 4,
                "orange_circles": 1,
            },
        ),
    }


def parse_json_text(text: str) -> Optional[dict[str, Any]]:
    if not text:
        return None

    t = text.strip()
    t = re.sub(r"^```(?:json)?\s*", "", t, flags=re.I)
    t = re.sub(r"\s*```$", "", t)

    try:
        obj = json.loads(t)
        return obj if isinstance(obj, dict) else None
    except Exception:
        pass

    a, b = t.find("{"), t.rfind("}")
    if a >= 0 and b > a:
        try:
            obj = json.loads(t[a : b + 1])
            return obj if isinstance(obj, dict) else None
        except Exception:
            pass

    return None


def norm_pos(value: Any) -> str:
    s = str(value or "").strip().lower().replace("_", "-").replace(" ", "-")
    if "右下" in s or ("bottom" in s and "right" in s):
        return "bottom-right"
    return s


def vision_check(obj: Optional[dict[str, Any]]) -> tuple[bool, str, dict[str, Any]]:
    if not isinstance(obj, dict):
        return False, "未得到可解析 JSON", {}

    ok = (
        obj.get("red_circles") == 3
        and obj.get("blue_squares") == 2
        and norm_pos(obj.get("green_triangle_position")) == "bottom-right"
        and "AI TEST 2026" in str(obj.get("text", "")).upper()
    )
    return (
        ok,
        "Vision Ground Truth 全部匹配" if ok else f"Vision Ground Truth 不完全匹配: {obj}",
        obj,
    )


def retry_after_seconds(response: requests.Response) -> Optional[float]:
    value = response.headers.get("Retry-After")
    if not value:
        return None
    try:
        return max(0.0, float(value))
    except Exception:
        return None


@dataclass
class Result:
    seq: int
    name: str
    category: str
    endpoint: str
    status: str
    http_status: Optional[int]
    elapsed_ms: Optional[float]
    ttft_ms: Optional[float]
    attempts: int
    recovered_by_retry: bool
    notes: str
    record_file: str
    stream_file: Optional[str] = None
    facts: Optional[dict[str, Any]] = None


class Suite:
    def __init__(
        self,
        base: str,
        key: str,
        model: str,
        out: Path,
        connect_timeout: int,
        read_timeout: int,
        retries: int,
        retry_backoff: float,
        max_backoff: float,
        retry_read_timeout: bool,
        inter_test_delay: float,
        heavy_cooldown: float,
        verify_tls: bool,
        context_len: int,
        remote_url: str = "",
        long_targets: Optional[list[int]] = None,
    ) -> None:
        base = base.rstrip("/")
        self.base = base[:-3] if base.endswith("/v1") else base

        self.key = key
        self.model = model
        self.out = out
        self.connect_timeout = connect_timeout
        self.read_timeout = read_timeout
        self.retries = max(0, retries)
        self.retry_backoff = max(0.0, retry_backoff)
        self.max_backoff = max(0.0, max_backoff)
        self.retry_read_timeout = retry_read_timeout
        self.inter_test_delay = max(0.0, inter_test_delay)
        self.heavy_cooldown = max(0.0, heavy_cooldown)
        self.verify_tls = verify_tls
        self.context_len = context_len
        self.remote_url = remote_url
        self.long_targets = long_targets or []

        self.records = out / "records"
        self.streams = out / "streams"
        self.assets_dir = out / "assets"

        for p in [self.records, self.streams, self.assets_dir]:
            p.mkdir(parents=True, exist_ok=True)

        self.assets = make_assets(self.assets_dir)
        self.s = requests.Session()

        self.seq = 0
        self.results: list[Result] = []
        self.detok_ids: list[int] = []
        self.token_text = "你好，Qwen3.6。这是一段用于 tokenizer 接口验证的中文测试文本。"

        self.chat_call: Optional[dict[str, Any]] = None
        self.resp_call: Optional[dict[str, Any]] = None
        self.anth_call: Optional[dict[str, Any]] = None

        if not verify_tls:
            try:
                requests.packages.urllib3.disable_warnings()  # type: ignore[attr-defined]
            except Exception:
                pass

    # ------------------------------------------------------------------
    # 基础工具
    # ------------------------------------------------------------------

    def url(self, ep: str) -> str:
        return self.base + ep

    def oh(self) -> dict[str, str]:
        h = {"Content-Type": "application/json"}
        if self.key:
            h["Authorization"] = "Bearer " + self.key
        return h

    def ah(self) -> dict[str, str]:
        h = {
            "Content-Type": "application/json",
            "anthropic-version": "2023-06-01",
        }
        if self.key:
            h["Authorization"] = "Bearer " + self.key
            h["x-api-key"] = self.key
        return h

    def next_seq(self) -> int:
        self.seq += 1
        return self.seq

    def delay(self, seconds: Optional[float] = None) -> None:
        sec = self.inter_test_delay if seconds is None else seconds
        if sec > 0:
            time.sleep(sec)

    def backoff_seconds(
        self,
        retry_index: int,
        response: Optional[requests.Response] = None,
    ) -> float:
        if response is not None:
            ra = retry_after_seconds(response)
            if ra is not None:
                return min(max(ra, self.retry_backoff), self.max_backoff)

        value = self.retry_backoff * (2 ** max(0, retry_index - 1))
        return min(value, self.max_backoff)

    def should_retry_exception(self, exc: BaseException) -> bool:
        if isinstance(exc, requests.exceptions.ReadTimeout):
            return self.retry_read_timeout

        retryable = (
            requests.exceptions.ConnectTimeout,
            requests.exceptions.ConnectionError,
            requests.exceptions.ChunkedEncodingError,
        )
        return isinstance(exc, retryable)

    def save(
        self,
        seq: int,
        name: str,
        req: dict[str, Any],
        resp: dict[str, Any],
        status: str,
        notes: str,
        facts: Optional[dict[str, Any]] = None,
    ) -> Path:
        p = self.records / f"{seq:02d}_{name}.json"
        doc = {
            "test": name,
            "recorded_at": now_iso(),
            "script": {
                "version": SCRIPT_VERSION,
                "sha256": script_sha256(),
            },
            "deployment": {
                "base_url": self.base,
                "model": self.model,
                "declared_context_length": self.context_len,
            },
            "retry_policy": {
                "retries": self.retries,
                "connect_timeout": self.connect_timeout,
                "read_timeout": self.read_timeout,
                "retry_backoff": self.retry_backoff,
                "max_backoff": self.max_backoff,
                "retry_read_timeout": self.retry_read_timeout,
                "retryable_http_status": sorted(RETRYABLE_HTTP_STATUS),
            },
            "request": redact(req, self.key),
            "response": redact(resp, self.key),
            "analysis": {
                "status": status,
                "notes": notes,
                "facts": facts or {},
            },
        }
        p.write_text(js(doc), encoding="utf-8")
        return p

    def add(
        self,
        *,
        seq: int,
        name: str,
        category: str,
        endpoint: str,
        status: str,
        code: Optional[int],
        elapsed_ms: Optional[float],
        ttft_ms: Optional[float],
        attempts: int,
        recovered_by_retry: bool,
        notes: str,
        record_file: Path,
        stream_file: Optional[Path] = None,
        facts: Optional[dict[str, Any]] = None,
    ) -> None:
        self.results.append(
            Result(
                seq=seq,
                name=name,
                category=category,
                endpoint=endpoint,
                status=status,
                http_status=code,
                elapsed_ms=elapsed_ms,
                ttft_ms=ttft_ms,
                attempts=attempts,
                recovered_by_retry=recovered_by_retry,
                notes=notes,
                record_file=record_file.name,
                stream_file=stream_file.name if stream_file else None,
                facts=facts,
            )
        )

        retry_tag = (
            f" attempts={attempts} RECOVERED"
            if recovered_by_retry
            else (f" attempts={attempts}" if attempts > 1 else "")
        )
        print(
            f"[{status:<5}] {seq:02d} {name:<31} "
            f"HTTP={str(code):<4} elapsed={str(elapsed_ms):<10} "
            f"ttft={str(ttft_ms):<10}{retry_tag}  {notes}"
        )

    def skip(self, name: str, category: str, ep: str, notes: str) -> None:
        seq = self.next_seq()
        req = {"method": "POST", "url": self.url(ep), "skipped": True}
        resp = {"skipped": True, "attempts": []}
        rec = self.save(seq, name, req, resp, "SKIP", notes)
        self.add(
            seq=seq,
            name=name,
            category=category,
            endpoint=ep,
            status="SKIP",
            code=None,
            elapsed_ms=None,
            ttft_ms=None,
            attempts=0,
            recovered_by_retry=False,
            notes=notes,
            record_file=rec,
        )

    # ------------------------------------------------------------------
    # 带重试的普通 HTTP 请求
    # ------------------------------------------------------------------

    def request(
        self,
        name: str,
        category: str,
        method: str,
        ep: str,
        body: Optional[dict[str, Any]] = None,
        headers: Optional[dict[str, str]] = None,
        check: Optional[
            Callable[[Any, requests.Response], tuple[bool, str, dict[str, Any]]]
        ] = None,
        read_timeout: Optional[int] = None,
    ) -> Any:
        seq = self.next_seq()
        headers = headers or self.oh()

        req = {
            "method": method,
            "url": self.url(ep),
            "headers": headers,
            "json": body,
        }

        attempts_log: list[dict[str, Any]] = []
        overall_start = time.perf_counter()
        final_response: Optional[requests.Response] = None
        final_data: Any = None
        final_exception: Optional[BaseException] = None

        max_attempts = 1 + self.retries

        for attempt in range(1, max_attempts + 1):
            attempt_start = time.perf_counter()
            try:
                r = self.s.request(
                    method,
                    self.url(ep),
                    headers=headers,
                    json=body if method.upper() in {"POST", "PUT", "PATCH"} else None,
                    timeout=(
                        self.connect_timeout,
                        read_timeout if read_timeout is not None else self.read_timeout,
                    ),
                    verify=self.verify_tls,
                )

                attempt_ms = round((time.perf_counter() - attempt_start) * 1000, 2)

                try:
                    data: Any = r.json()
                except Exception:
                    data = r.text

                attempts_log.append(
                    {
                        "attempt": attempt,
                        "status_code": r.status_code,
                        "elapsed_ms": attempt_ms,
                        "retryable_http_status": r.status_code in RETRYABLE_HTTP_STATUS,
                    }
                )

                final_response = r
                final_data = data

                if (
                    r.status_code in RETRYABLE_HTTP_STATUS
                    and attempt < max_attempts
                ):
                    wait = self.backoff_seconds(attempt, r)
                    attempts_log[-1]["will_retry"] = True
                    attempts_log[-1]["backoff_seconds"] = wait
                    print(
                        f"  ↳ {name}: HTTP {r.status_code}，"
                        f"{wait:g}s 后重试 ({attempt}/{max_attempts})"
                    )
                    time.sleep(wait)
                    continue

                break

            except Exception as exc:
                attempt_ms = round((time.perf_counter() - attempt_start) * 1000, 2)
                retryable = self.should_retry_exception(exc)

                attempts_log.append(
                    {
                        "attempt": attempt,
                        "status_code": None,
                        "elapsed_ms": attempt_ms,
                        "exception": f"{type(exc).__name__}: {exc}",
                        "retryable_exception": retryable,
                    }
                )

                final_exception = exc

                if retryable and attempt < max_attempts:
                    wait = self.backoff_seconds(attempt)
                    attempts_log[-1]["will_retry"] = True
                    attempts_log[-1]["backoff_seconds"] = wait
                    print(
                        f"  ↳ {name}: {type(exc).__name__}，"
                        f"{wait:g}s 后重试 ({attempt}/{max_attempts})"
                    )
                    time.sleep(wait)
                    continue

                break

        total_ms = round((time.perf_counter() - overall_start) * 1000, 2)
        attempt_count = len(attempts_log)
        recovered = (
            attempt_count > 1
            and final_response is not None
            and 200 <= final_response.status_code < 300
        )

        if final_response is None:
            notes = (
                f"{type(final_exception).__name__}: {final_exception}"
                if final_exception is not None
                else "请求未得到 HTTP Response"
            )
            resp_info = {
                "status_code": None,
                "elapsed_ms": total_ms,
                "attempts": attempts_log,
                "exception": notes,
                "traceback": traceback.format_exc() if final_exception else None,
            }
            rec = self.save(seq, name, req, resp_info, "ERROR", notes)
            self.add(
                seq=seq,
                name=name,
                category=category,
                endpoint=ep,
                status="ERROR",
                code=None,
                elapsed_ms=total_ms,
                ttft_ms=None,
                attempts=attempt_count,
                recovered_by_retry=False,
                notes=notes,
                record_file=rec,
            )
            self.delay()
            return None

        r = final_response
        data = final_data

        ok = 200 <= r.status_code < 300
        notes = "HTTP 2xx"
        facts: dict[str, Any] = {}

        if ok and check:
            try:
                ok, notes, facts = check(data, r)
            except Exception as exc:
                ok = False
                notes = f"判定程序异常: {type(exc).__name__}: {exc}"
                facts = {
                    "checker_exception": True,
                    "checker_exception_type": type(exc).__name__,
                }
        elif not ok:
            notes = f"HTTP {r.status_code}"
            if r.status_code in {400, 401, 403, 404, 409, 422}:
                notes += "（明确客户端/协议错误，不自动重试）"

        status = "PASS" if ok else "FAIL"

        if recovered:
            notes = f"{notes}；网络/服务异常后第 {attempt_count} 次尝试恢复"

        resp_info = {
            "status_code": r.status_code,
            "elapsed_ms": total_ms,
            "headers": dict(r.headers),
            "body": data,
            "attempts": attempts_log,
            "recovered_by_retry": recovered,
        }

        rec = self.save(seq, name, req, resp_info, status, notes, facts)

        self.add(
            seq=seq,
            name=name,
            category=category,
            endpoint=ep,
            status=status,
            code=r.status_code,
            elapsed_ms=total_ms,
            ttft_ms=None,
            attempts=attempt_count,
            recovered_by_retry=recovered,
            notes=notes,
            record_file=rec,
            facts=facts,
        )

        self.delay()
        return data

    # ------------------------------------------------------------------
    # 带重试的 SSE
    # ------------------------------------------------------------------

    def stream(
        self,
        name: str,
        category: str,
        ep: str,
        body: dict[str, Any],
        headers: dict[str, str],
        mode: str,
        events: Optional[list[str]] = None,
        markers: Optional[list[str]] = None,
        validate: Optional[
            Callable[[str], tuple[bool, str, dict[str, Any]]]
        ] = None,
    ) -> str:
        seq = self.next_seq()

        req = {
            "method": "POST",
            "url": self.url(ep),
            "headers": headers,
            "json": body,
        }

        max_attempts = 1 + self.retries
        attempts_log: list[dict[str, Any]] = []
        overall_start = time.perf_counter()

        final_raw: list[str] = []
        final_events: list[str] = []
        final_parts: list[str] = []
        final_code: Optional[int] = None
        final_first_content_ms: Optional[float] = None
        final_exception: Optional[BaseException] = None
        final_stream_file: Optional[Path] = None
        recovered = False

        for attempt in range(1, max_attempts + 1):
            raw: list[str] = []
            evs: list[str] = []
            parts: list[str] = []
            first_content_ms: Optional[float] = None
            attempt_start = time.perf_counter()
            code: Optional[int] = None

            try:
                with self.s.post(
                    self.url(ep),
                    headers=headers,
                    json=body,
                    stream=True,
                    timeout=(self.connect_timeout, self.read_timeout),
                    verify=self.verify_tls,
                ) as r:
                    code = r.status_code

                    if (
                        code in RETRYABLE_HTTP_STATUS
                        and attempt < max_attempts
                    ):
                        attempt_ms = round(
                            (time.perf_counter() - attempt_start) * 1000, 2
                        )
                        wait = self.backoff_seconds(attempt, r)
                        attempts_log.append(
                            {
                                "attempt": attempt,
                                "status_code": code,
                                "elapsed_ms": attempt_ms,
                                "received_stream_lines": 0,
                                "will_retry": True,
                                "backoff_seconds": wait,
                            }
                        )
                        print(
                            f"  ↳ {name}: SSE HTTP {code}，"
                            f"{wait:g}s 后重试 ({attempt}/{max_attempts})"
                        )
                        time.sleep(wait)
                        continue

                    for line in r.iter_lines(decode_unicode=True):
                        if line is None:
                            continue

                        raw.append(line)

                        if line.startswith("event:"):
                            evs.append(line.split(":", 1)[1].strip())
                            continue

                        if not line.startswith("data:"):
                            continue

                        payload = line.split(":", 1)[1].strip()
                        if payload == "[DONE]":
                            continue

                        try:
                            obj = json.loads(payload)
                        except Exception:
                            continue

                        piece = ""

                        if mode == "chat":
                            try:
                                piece = (
                                    obj["choices"][0]["delta"].get("content") or ""
                                )
                            except Exception:
                                pass

                        elif (
                            mode == "responses"
                            and obj.get("type") == "response.output_text.delta"
                        ):
                            piece = obj.get("delta") or ""

                        elif (
                            mode == "anthropic"
                            and obj.get("type") == "content_block_delta"
                        ):
                            delta = obj.get("delta") or {}
                            if delta.get("type") == "text_delta":
                                piece = delta.get("text") or ""

                        if piece:
                            if first_content_ms is None:
                                first_content_ms = round(
                                    (time.perf_counter() - attempt_start) * 1000,
                                    2,
                                )
                            parts.append(piece)

                attempt_ms = round(
                    (time.perf_counter() - attempt_start) * 1000, 2
                )
                attempts_log.append(
                    {
                        "attempt": attempt,
                        "status_code": code,
                        "elapsed_ms": attempt_ms,
                        "received_stream_lines": len(raw),
                        "received_text_chars": len("".join(parts)),
                    }
                )

                final_raw = raw
                final_events = evs
                final_parts = parts
                final_code = code
                final_first_content_ms = first_content_ms
                recovered = attempt > 1
                break

            except Exception as exc:
                attempt_ms = round(
                    (time.perf_counter() - attempt_start) * 1000, 2
                )
                received_any = bool(raw or evs or parts)
                retryable = self.should_retry_exception(exc) and not received_any

                attempts_log.append(
                    {
                        "attempt": attempt,
                        "status_code": code,
                        "elapsed_ms": attempt_ms,
                        "exception": f"{type(exc).__name__}: {exc}",
                        "received_stream_lines": len(raw),
                        "received_text_chars": len("".join(parts)),
                        "retryable": retryable,
                    }
                )

                # 无论是否重试，都保留该 attempt 的部分 SSE
                if raw:
                    attempt_file = (
                        self.streams
                        / f"{seq:02d}_{name}_attempt_{attempt}_partial.sse.txt"
                    )
                    attempt_file.write_text("\n".join(raw), encoding="utf-8")
                    attempts_log[-1]["partial_stream_file"] = attempt_file.name

                final_exception = exc
                final_raw = raw
                final_events = evs
                final_parts = parts
                final_code = code
                final_first_content_ms = first_content_ms

                if retryable and attempt < max_attempts:
                    wait = self.backoff_seconds(attempt)
                    attempts_log[-1]["will_retry"] = True
                    attempts_log[-1]["backoff_seconds"] = wait
                    print(
                        f"  ↳ {name}: SSE {type(exc).__name__} 且尚未收到有效流，"
                        f"{wait:g}s 后重试 ({attempt}/{max_attempts})"
                    )
                    time.sleep(wait)
                    continue

                # 一旦收到部分流，自动重试会把两次输出混在一起，所以直接停止。
                break

        total_ms = round((time.perf_counter() - overall_start) * 1000, 2)
        text = "".join(final_parts)
        raw_text = "\n".join(final_raw)

        if final_raw:
            final_stream_file = self.streams / f"{seq:02d}_{name}.sse.txt"
            final_stream_file.write_text(raw_text, encoding="utf-8")

        if final_code is None:
            notes = (
                f"{type(final_exception).__name__}: {final_exception}"
                if final_exception is not None
                else "SSE 未得到 HTTP Response"
            )
            status = "ERROR"
            facts: dict[str, Any] = {
                "events": final_events,
                "reconstructed_text": text,
            }

        else:
            required_events = events or []
            missing = [x for x in required_events if x not in final_events]
            marker_ok = (
                True
                if not markers
                else any(marker in raw_text for marker in markers)
            )

            ok = 200 <= final_code < 300 and not missing and marker_ok
            notes = "流式协议通过"
            facts = {
                "events": final_events,
                "reconstructed_text": text,
            }

            if ok and validate:
                try:
                    ok, notes, extra = validate(text)
                    facts.update(extra)
                except Exception as exc:
                    ok = False
                    notes = f"流式判定程序异常: {type(exc).__name__}: {exc}"
                    facts["checker_exception"] = True

            elif not ok:
                if final_code in {400, 401, 403, 404, 409, 422}:
                    notes = (
                        f"HTTP {final_code}，明确客户端/协议错误，不自动重试"
                    )
                else:
                    notes = (
                        f"缺少事件={missing} 或完成标记，"
                        f"HTTP={final_code}"
                    )

            status = "PASS" if ok else "FAIL"

        if recovered and status == "PASS":
            notes += f"；第 {len(attempts_log)} 次尝试恢复"

        resp_info = {
            "status_code": final_code,
            "elapsed_ms": total_ms,
            "first_content_ms": final_first_content_ms,
            "events": final_events,
            "reconstructed_text": text,
            "attempts": attempts_log,
            "recovered_by_retry": recovered,
            "raw_sse_file": final_stream_file.name if final_stream_file else None,
        }

        if final_exception is not None:
            resp_info["last_exception"] = (
                f"{type(final_exception).__name__}: {final_exception}"
            )

        rec = self.save(seq, name, req, resp_info, status, notes, facts)

        self.add(
            seq=seq,
            name=name,
            category=category,
            endpoint=ep,
            status=status,
            code=final_code,
            elapsed_ms=total_ms,
            ttft_ms=final_first_content_ms,
            attempts=len(attempts_log),
            recovered_by_retry=recovered and status == "PASS",
            notes=notes,
            record_file=rec,
            stream_file=final_stream_file,
            facts=facts,
        )

        self.delay()
        return text

    # ------------------------------------------------------------------
    # 基础接口
    # ------------------------------------------------------------------

    def basic(self) -> None:
        def model_check(data: Any, _: requests.Response):
            models = data.get("data", []) if isinstance(data, dict) else []
            model = next(
                (
                    x
                    for x in models
                    if isinstance(x, dict) and x.get("id") == self.model
                ),
                None,
            )
            return (
                bool(model),
                (
                    f"找到 {self.model}, max_model_len={model.get('max_model_len')}"
                    if model
                    else "未找到模型"
                ),
                model or {},
            )

        self.request(
            "models",
            "基础接口",
            "GET",
            "/v1/models",
            headers=self.oh(),
            check=model_check,
        )

        self.request(
            "version",
            "基础接口",
            "GET",
            "/version",
            headers=self.oh(),
            check=lambda d, _: (
                bool(d),
                f"version={d.get('version') if isinstance(d, dict) else d}",
                {},
            ),
        )

        self.metrics("before")

        def openapi_check(data: Any, _: requests.Response):
            paths = (
                sorted((data.get("paths") or {}).keys())
                if isinstance(data, dict)
                else []
            )
            (self.out / "openapi_paths.txt").write_text(
                "\n".join(paths),
                encoding="utf-8",
            )
            ok = (
                isinstance(data, dict)
                and "openapi" in data
                and "paths" in data
            )
            return ok, f"OpenAPI paths={len(paths)}", {"paths": paths}

        self.request(
            "openapi",
            "基础接口",
            "GET",
            "/openapi.json",
            headers=self.oh(),
            check=openapi_check,
        )

        tokenize_body = {
            "model": self.model,
            "prompt": self.token_text,
            "add_special_tokens": False,
            "return_token_strs": True,
        }

        def tokenize_check(data: Any, _: requests.Response):
            self.detok_ids = (
                data.get("tokens") or []
                if isinstance(data, dict)
                else []
            )
            return (
                bool(self.detok_ids),
                (
                    f"count={data.get('count')}, "
                    f"max_model_len={data.get('max_model_len')}"
                    if isinstance(data, dict)
                    else "tokenize 返回异常"
                ),
                {
                    "count": data.get("count")
                    if isinstance(data, dict)
                    else None
                },
            )

        self.request(
            "tokenize",
            "Tokenizer",
            "POST",
            "/tokenize",
            tokenize_body,
            self.oh(),
            tokenize_check,
        )

        if self.detok_ids:
            self.request(
                "detokenize",
                "Tokenizer",
                "POST",
                "/detokenize",
                {"model": self.model, "tokens": self.detok_ids},
                self.oh(),
                lambda d, _: (
                    d.get("prompt") == self.token_text,
                    (
                        "与原文一致"
                        if d.get("prompt") == self.token_text
                        else "与原文不一致"
                    ),
                    {},
                ),
            )
        else:
            self.skip(
                "detokenize",
                "Tokenizer",
                "/detokenize",
                "前置 tokenize 未获得 token IDs",
            )

        self.request(
            "anthropic_count_tokens",
            "Claude / Anthropic",
            "POST",
            "/v1/messages/count_tokens",
            {
                "model": self.model,
                "messages": [{"role": "user", "content": "count tokens test"}],
            },
            self.ah(),
            lambda d, _: (
                (
                    isinstance(d, dict)
                    and isinstance(d.get("input_tokens"), int)
                ),
                (
                    f"input_tokens={d.get('input_tokens')}"
                    if isinstance(d, dict)
                    else "count_tokens 返回异常"
                ),
                {
                    "input_tokens": d.get("input_tokens")
                    if isinstance(d, dict)
                    else None
                },
            ),
        )

    def metrics(self, suffix: str) -> None:
        def check(data: Any, _: requests.Response):
            text = data if isinstance(data, str) else js(data)
            keys = [
                "vllm:num_requests_running",
                "vllm:num_requests_waiting",
                "vllm:kv_cache_usage_perc",
                "vllm:prefix_cache_hits_total",
                "vllm:prompt_tokens_total",
            ]
            found = [k for k in keys if k in text]
            return (
                "# HELP" in text or "vllm:" in text,
                f"关键指标 {len(found)}/{len(keys)}",
                {"found": found},
            )

        self.request(
            f"metrics_{suffix}",
            "基础接口",
            "GET",
            "/metrics",
            headers=self.oh(),
            check=check,
        )

    # ------------------------------------------------------------------
    # OpenAI Chat
    # ------------------------------------------------------------------

    def chat(self) -> None:
        body = {
            "model": self.model,
            "messages": [{"role": "user", "content": "请只回答：CHAT_OK"}],
            "temperature": 0,
            "max_tokens": 128,
            "stream": False,
            "chat_template_kwargs": {"enable_thinking": False},
        }

        self.request(
            "chat_nonstream",
            "OpenAI Chat",
            "POST",
            "/v1/chat/completions",
            body,
            self.oh(),
            lambda d, _: (
                "CHAT_OK"
                in ((d["choices"][0]["message"].get("content") or "")),
                "chat.completion 正常",
                {"usage": d.get("usage")},
            ),
        )

        stream_body = dict(body)
        stream_body["stream"] = True
        stream_body["messages"] = [
            {"role": "user", "content": "请只回答：CHAT_STREAM_OK"}
        ]

        self.stream(
            "chat_stream",
            "OpenAI Chat",
            "/v1/chat/completions",
            stream_body,
            self.oh(),
            "chat",
            markers=["[DONE]", "finish_reason"],
            validate=lambda text: (
                "CHAT_STREAM_OK" in text,
                "流式文本正确",
                {"text": text},
            ),
        )

        puzzle = (
            "三个盒子标签全错，只能取一个水果，如何确定标签？"
            "请给出答案。"
        )

        off = {
            "model": self.model,
            "messages": [{"role": "user", "content": puzzle}],
            "temperature": 0.1,
            "max_tokens": 512,
            "chat_template_kwargs": {"enable_thinking": False},
        }

        def off_check(data: Any, _: requests.Response):
            choice = data["choices"][0]
            message = choice["message"]
            reasoning = (
                message.get("reasoning")
                or message.get("reasoning_content")
            )
            return (
                bool(message.get("content")) and not reasoning,
                "Thinking OFF 检测完成",
                {
                    "finish_reason": choice.get("finish_reason"),
                    "usage": data.get("usage"),
                    "reasoning_present": bool(reasoning),
                },
            )

        self.request(
            "chat_thinking_off",
            "Thinking",
            "POST",
            "/v1/chat/completions",
            off,
            self.oh(),
            off_check,
        )

        on = dict(off)
        on["max_tokens"] = 1536
        on["chat_template_kwargs"] = {"enable_thinking": True}

        def on_check(data: Any, _: requests.Response):
            choice = data["choices"][0]
            message = choice["message"]
            reasoning = (
                message.get("reasoning")
                or message.get("reasoning_content")
            )
            return (
                bool(reasoning),
                (
                    "Thinking ON 检测到 reasoning"
                    if reasoning
                    else "未检测到 reasoning"
                ),
                {
                    "finish_reason": choice.get("finish_reason"),
                    "usage": data.get("usage"),
                    "reasoning_present": bool(reasoning),
                },
            )

        self.request(
            "chat_thinking_on",
            "Thinking",
            "POST",
            "/v1/chat/completions",
            on,
            self.oh(),
            on_check,
        )

        # Thinking 是重请求，主动给共享服务一点恢复时间。
        self.delay(self.heavy_cooldown)

        tool = {
            "type": "function",
            "function": {
                "name": "get_weather",
                "description": "查询城市天气",
                "parameters": {
                    "type": "object",
                    "properties": {"city": {"type": "string"}},
                    "required": ["city"],
                    "additionalProperties": False,
                },
            },
        }

        tool_body = {
            "model": self.model,
            "messages": [
                {
                    "role": "user",
                    "content": "查询北京天气，必须调用 get_weather。",
                }
            ],
            "max_tokens": 512,
            "chat_template_kwargs": {"enable_thinking": False},
            "tools": [tool],
            "tool_choice": "required",
        }

        def tool_check(data: Any, _: requests.Response):
            message = data["choices"][0]["message"]
            calls = message.get("tool_calls") or []

            if not calls:
                return False, "没有 tool_calls", {}

            fn = calls[0]["function"]
            args = json.loads(fn.get("arguments") or "{}")
            ok = (
                fn.get("name") == "get_weather"
                and args.get("city") in {"北京", "北京市", "Beijing"}
            )

            if ok:
                self.chat_call = {
                    "role": "assistant",
                    "content": message.get("content"),
                    "tool_calls": calls,
                }

            return (
                ok,
                "Chat Tool Call 正确",
                {
                    "arguments": args,
                    "tool_call_id": calls[0].get("id"),
                },
            )

        self.request(
            "chat_tool_call",
            "OpenAI Chat / Agent",
            "POST",
            "/v1/chat/completions",
            tool_body,
            self.oh(),
            tool_check,
        )

        if self.chat_call:
            call = self.chat_call["tool_calls"][0]
            result = {
                "city": "北京",
                "temperature": 23,
                "weather": "晴",
            }

            loop_body = {
                "model": self.model,
                "messages": [
                    {
                        "role": "user",
                        "content": "查询北京天气，必须调用 get_weather。",
                    },
                    self.chat_call,
                    {
                        "role": "tool",
                        "tool_call_id": call["id"],
                        "content": json.dumps(result, ensure_ascii=False),
                    },
                ],
                "max_tokens": 256,
                "chat_template_kwargs": {"enable_thinking": False},
                "tools": [tool],
                "tool_choice": "auto",
            }

            def loop_check(data: Any, _: requests.Response):
                message = data["choices"][0]["message"]
                text = message.get("content") or ""
                ok = (
                    "23" in text
                    and ("晴" in text or "sunny" in text.lower())
                    and not (message.get("tool_calls") or [])
                )
                return (
                    ok,
                    "Chat Tool Result 闭环完成"
                    if ok
                    else f"闭环异常: {text}",
                    {"text": text},
                )

            self.request(
                "chat_tool_result_loop",
                "OpenAI Chat / Agent",
                "POST",
                "/v1/chat/completions",
                loop_body,
                self.oh(),
                loop_check,
            )

        else:
            self.skip(
                "chat_tool_result_loop",
                "OpenAI Chat / Agent",
                "/v1/chat/completions",
                "前置 Tool Call 失败",
            )

    # ------------------------------------------------------------------
    # OpenAI Responses
    # ------------------------------------------------------------------

    def responses(self) -> None:
        def text_of(data: Any) -> str:
            out = []
            if isinstance(data, dict):
                for item in data.get("output", []):
                    if item.get("type") == "message":
                        for content in item.get("content", []):
                            if content.get("type") == "output_text":
                                out.append(content.get("text") or "")
            return "".join(out)

        body = {
            "model": self.model,
            "input": "请只回答：RESPONSES_OK",
            "max_output_tokens": 256,
            "reasoning": {"effort": "none"},
        }

        self.request(
            "responses_nonstream",
            "Codex / Responses",
            "POST",
            "/v1/responses",
            body,
            self.oh(),
            lambda d, _: (
                (
                    d.get("object") == "response"
                    and "RESPONSES_OK" in text_of(d)
                ),
                "Responses 文本正确",
                {
                    "status": d.get("status"),
                    "usage": d.get("usage"),
                },
            ),
        )

        stream_body = dict(body)
        stream_body["stream"] = True
        stream_body["input"] = "请只回答：RESPONSES_STREAM_OK"

        self.stream(
            "responses_stream",
            "Codex / Responses",
            "/v1/responses",
            stream_body,
            self.oh(),
            "responses",
            ["response.created", "response.completed"],
            ["response.completed"],
            lambda text: (
                "RESPONSES_STREAM_OK" in text,
                "Responses SSE 文本正确",
                {"text": text},
            ),
        )

        tool = {
            "type": "function",
            "name": "get_weather",
            "description": "查询城市天气",
            "parameters": {
                "type": "object",
                "properties": {"city": {"type": "string"}},
                "required": ["city"],
                "additionalProperties": False,
            },
        }

        tool_body = {
            "model": self.model,
            "input": "查询北京天气，必须调用 get_weather。",
            "max_output_tokens": 512,
            "reasoning": {"effort": "none"},
            "tools": [tool],
            "tool_choice": "required",
            "parallel_tool_calls": False,
        }

        def tool_check(data: Any, _: requests.Response):
            calls = [
                x
                for x in data.get("output", [])
                if x.get("type") == "function_call"
            ]

            if not calls:
                return False, "没有 function_call", {}

            call = calls[0]
            args = json.loads(call.get("arguments") or "{}")
            ok = (
                call.get("name") == "get_weather"
                and args.get("city") in {"北京", "北京市", "Beijing"}
            )

            if ok:
                self.resp_call = call

            return (
                ok,
                "Responses function_call 正确",
                {
                    "arguments": args,
                    "call_id": call.get("call_id"),
                },
            )

        self.request(
            "responses_tool_call",
            "Codex / Responses",
            "POST",
            "/v1/responses",
            tool_body,
            self.oh(),
            tool_check,
        )

        if self.resp_call:
            result = {
                "city": "北京",
                "temperature": 23,
                "weather": "晴",
            }

            loop_body = {
                "model": self.model,
                "input": [
                    {
                        "role": "user",
                        "content": "查询北京天气，必须调用 get_weather。",
                    },
                    self.resp_call,
                    {
                        "type": "function_call_output",
                        "call_id": self.resp_call.get("call_id"),
                        "output": json.dumps(result, ensure_ascii=False),
                    },
                ],
                "max_output_tokens": 256,
                "reasoning": {"effort": "none"},
                "tools": [tool],
                "tool_choice": "auto",
            }

            def loop_check(data: Any, _: requests.Response):
                text = text_of(data)
                calls = [
                    x
                    for x in data.get("output", [])
                    if x.get("type") == "function_call"
                ]
                ok = (
                    "23" in text
                    and ("晴" in text or "sunny" in text.lower())
                    and not calls
                )
                return (
                    ok,
                    "Responses Tool Result 闭环完成"
                    if ok
                    else f"闭环异常: {text}",
                    {"text": text},
                )

            self.request(
                "responses_tool_result_loop",
                "Codex / Responses",
                "POST",
                "/v1/responses",
                loop_body,
                self.oh(),
                loop_check,
            )

        else:
            self.skip(
                "responses_tool_result_loop",
                "Codex / Responses",
                "/v1/responses",
                "前置 function_call 失败",
            )

    # ------------------------------------------------------------------
    # Anthropic Messages
    # ------------------------------------------------------------------

    def anthropic(self) -> None:
        def text_blocks(data: Any) -> str:
            if not isinstance(data, dict):
                return ""
            return "".join(
                x.get("text") or ""
                for x in (data.get("content") or [])
                if isinstance(x, dict) and x.get("type") == "text"
            )

        body = {
            "model": self.model,
            "max_tokens": 384,
            "thinking": {"type": "disabled"},
            "messages": [
                {"role": "user", "content": "请只回答：CLAUDE_OK"}
            ],
        }

        def message_check(data: Any, _: requests.Response):
            blocks = data.get("content") or []
            thinking_count = sum(
                1
                for x in blocks
                if isinstance(x, dict) and x.get("type") == "thinking"
            )
            text = text_blocks(data)
            ok = (
                data.get("type") == "message"
                and "CLAUDE_OK" in text
            )
            note = "Anthropic 文本正确"
            if thinking_count:
                note += "；disabled 后仍出现 thinking"

            return (
                ok,
                note,
                {
                    "thinking_blocks": thinking_count,
                    "thinking_disabled_effective": thinking_count == 0,
                    "stop_reason": data.get("stop_reason"),
                    "usage": data.get("usage"),
                },
            )

        self.request(
            "anthropic_nonstream",
            "Claude / Anthropic",
            "POST",
            "/v1/messages",
            body,
            self.ah(),
            message_check,
        )

        stream_body = dict(body)
        stream_body["stream"] = True
        stream_body["messages"] = [
            {"role": "user", "content": "请只回答：CLAUDE_STREAM_OK"}
        ]

        self.stream(
            "anthropic_stream",
            "Claude / Anthropic",
            "/v1/messages",
            stream_body,
            self.ah(),
            "anthropic",
            ["message_start", "message_stop"],
            ["message_stop"],
            lambda text: (
                "CLAUDE_STREAM_OK" in text,
                "Anthropic SSE 文本正确",
                {"text": text},
            ),
        )

        tool = {
            "name": "get_weather",
            "description": "查询城市天气",
            "input_schema": {
                "type": "object",
                "properties": {"city": {"type": "string"}},
                "required": ["city"],
                "additionalProperties": False,
            },
        }

        tool_body = {
            "model": self.model,
            "max_tokens": 1536,
            "thinking": {"type": "disabled"},
            "messages": [
                {
                    "role": "user",
                    "content": "查询北京天气，必须使用 get_weather。",
                }
            ],
            "tools": [tool],
            "tool_choice": {"type": "any"},
        }

        def tool_check(data: Any, _: requests.Response):
            blocks = (
                data.get("content") or []
                if isinstance(data, dict)
                else []
            )
            calls = [
                x
                for x in blocks
                if isinstance(x, dict) and x.get("type") == "tool_use"
            ]
            thinking_count = sum(
                1
                for x in blocks
                if isinstance(x, dict) and x.get("type") == "thinking"
            )
            stop_reason = (
                data.get("stop_reason")
                if isinstance(data, dict)
                else None
            )

            if not calls:
                if stop_reason == "tool_use":
                    note = (
                        "协议结构不一致：stop_reason=tool_use，"
                        "但 content[] 中没有标准 tool_use block"
                    )
                else:
                    note = f"未返回 tool_use；stop_reason={stop_reason}"

                return (
                    False,
                    note,
                    {
                        "usage": data.get("usage")
                        if isinstance(data, dict)
                        else None,
                        "stop_reason": stop_reason,
                        "thinking_block_count": thinking_count,
                        "protocol_inconsistency": stop_reason == "tool_use",
                    },
                )

            call = calls[0]
            inp = call.get("input") or {}
            ok = (
                call.get("name") == "get_weather"
                and inp.get("city") in {"北京", "北京市", "Beijing"}
            )

            if ok:
                self.anth_call = call

            return (
                ok,
                "Anthropic tool_use 正确",
                {
                    "input": inp,
                    "tool_use_id": call.get("id"),
                    "stop_reason": stop_reason,
                    "thinking_block_count": thinking_count,
                    "protocol_inconsistency": False,
                },
            )

        self.request(
            "anthropic_tool_use",
            "Claude / Anthropic",
            "POST",
            "/v1/messages",
            tool_body,
            self.ah(),
            tool_check,
        )

        if self.anth_call:
            result = {
                "city": "北京",
                "temperature": 23,
                "weather": "晴",
            }

            loop_body = {
                "model": self.model,
                "max_tokens": 768,
                "thinking": {"type": "disabled"},
                "messages": [
                    {
                        "role": "user",
                        "content": "查询北京天气，必须使用 get_weather。",
                    },
                    {
                        "role": "assistant",
                        "content": [self.anth_call],
                    },
                    {
                        "role": "user",
                        "content": [
                            {
                                "type": "tool_result",
                                "tool_use_id": self.anth_call.get("id"),
                                "content": json.dumps(
                                    result,
                                    ensure_ascii=False,
                                ),
                            }
                        ],
                    },
                ],
                "tools": [tool],
            }

            def loop_check(data: Any, _: requests.Response):
                text = text_blocks(data)
                calls = [
                    x
                    for x in (data.get("content") or [])
                    if isinstance(x, dict) and x.get("type") == "tool_use"
                ]
                ok = (
                    "23" in text
                    and ("晴" in text or "sunny" in text.lower())
                    and not calls
                )
                return (
                    ok,
                    "Anthropic Tool Result 闭环完成"
                    if ok
                    else f"闭环异常: {text}",
                    {"text": text},
                )

            self.request(
                "anthropic_tool_result_loop",
                "Claude / Anthropic",
                "POST",
                "/v1/messages",
                loop_body,
                self.ah(),
                loop_check,
            )

        else:
            self.skip(
                "anthropic_tool_result_loop",
                "Claude / Anthropic",
                "/v1/messages",
                "前置 tool_use 失败",
            )

        # Anthropic 当前会出现 disabled thinking 不生效，属于潜在重请求。
        self.delay(self.heavy_cooldown)

    # ------------------------------------------------------------------
    # Vision
    # ------------------------------------------------------------------

    def uri(self, name: str) -> str:
        return "data:image/png;base64," + self.assets[name]["b64"]

    def vision_prompt(self) -> str:
        return (
            '只输出 JSON，不要解释：'
            '{"red_circles":整数,"blue_squares":整数,'
            '"green_triangle_position":"bottom-right 或其他位置",'
            '"text":"顶部文字"}'
        )

    def vision(self) -> None:
        body = {
            "model": self.model,
            "messages": [
                {
                    "role": "user",
                    "content": [
                        {"type": "text", "text": self.vision_prompt()},
                        {
                            "type": "image_url",
                            "image_url": {"url": self.uri("image1")},
                        },
                    ],
                }
            ],
            "temperature": 0,
            "max_tokens": 512,
            "chat_template_kwargs": {"enable_thinking": False},
        }

        def single_check(data: Any, _: requests.Response):
            text = data["choices"][0]["message"].get("content") or ""
            obj = parse_json_text(text)
            ok, note, facts = vision_check(obj)
            facts["raw_text"] = text
            return ok, note, facts

        self.request(
            "vision_chat_base64",
            "Vision / OpenAI Chat",
            "POST",
            "/v1/chat/completions",
            body,
            self.oh(),
            single_check,
        )

        stream_body = {
            "model": self.model,
            "messages": [
                {
                    "role": "user",
                    "content": [
                        {
                            "type": "text",
                            "text": '只输出 JSON：{"red_circles":整数}',
                        },
                        {
                            "type": "image_url",
                            "image_url": {"url": self.uri("image1")},
                        },
                    ],
                }
            ],
            "temperature": 0,
            "max_tokens": 128,
            "stream": True,
            "chat_template_kwargs": {"enable_thinking": False},
        }

        def stream_vision_check(text: str):
            obj = parse_json_text(text)
            ok = (
                isinstance(obj, dict)
                and obj.get("red_circles") == 3
            )
            return (
                ok,
                "Vision SSE 识别正确"
                if ok
                else f"Vision SSE 异常: {text}",
                {"parsed": obj},
            )

        self.stream(
            "vision_chat_stream",
            "Vision / OpenAI Chat",
            "/v1/chat/completions",
            stream_body,
            self.oh(),
            "chat",
            markers=["[DONE]", "finish_reason"],
            validate=stream_vision_check,
        )

        multi_body = {
            "model": self.model,
            "messages": [
                {
                    "role": "user",
                    "content": [
                        {
                            "type": "text",
                            "text": (
                                '两张图，只输出 JSON：'
                                '{"image1_red_circles":整数,'
                                '"image1_text":"文字",'
                                '"image2_purple_squares":整数,'
                                '"image2_orange_circles":整数,'
                                '"image2_text":"文字"}\n第一张：'
                            ),
                        },
                        {
                            "type": "image_url",
                            "image_url": {"url": self.uri("image1")},
                        },
                        {"type": "text", "text": "\n第二张："},
                        {
                            "type": "image_url",
                            "image_url": {"url": self.uri("image2")},
                        },
                    ],
                }
            ],
            "temperature": 0,
            "max_tokens": 512,
            "chat_template_kwargs": {"enable_thinking": False},
        }

        def multi_check(data: Any, _: requests.Response):
            text = data["choices"][0]["message"].get("content") or ""
            obj = parse_json_text(text)
            ok = (
                isinstance(obj, dict)
                and obj.get("image1_red_circles") == 3
                and "AI TEST 2026"
                in str(obj.get("image1_text", "")).upper()
                and obj.get("image2_purple_squares") == 4
                and obj.get("image2_orange_circles") == 1
                and "SECOND IMAGE"
                in str(obj.get("image2_text", "")).upper()
            )
            return (
                ok,
                "多图 Ground Truth 匹配"
                if ok
                else f"多图异常: {obj}",
                {"parsed": obj},
            )

        self.request(
            "vision_multi_image",
            "Vision / OpenAI Chat",
            "POST",
            "/v1/chat/completions",
            multi_body,
            self.oh(),
            multi_check,
        )

        # Vision + Tool：字段名明确，不再使用含义模糊的 text。
        visual_tool = {
            "type": "function",
            "function": {
                "name": "submit_visual_observation",
                "description": "提交测试图片中的结构化视觉事实",
                "parameters": {
                    "type": "object",
                    "properties": {
                        "red_circles": {
                            "type": "integer",
                            "description": "图片中红色圆形数量",
                        },
                        "blue_squares": {
                            "type": "integer",
                            "description": "图片中蓝色正方形数量",
                        },
                        "green_triangle_position": {
                            "type": "string",
                            "description": "绿色三角形位置，例如 bottom-right",
                        },
                        "top_text": {
                            "type": "string",
                            "description": (
                                "必须逐字 OCR 图片顶部黑色英文文字，"
                                "只能填写文字本身，不得填写图片描述"
                            ),
                        },
                    },
                    "required": [
                        "red_circles",
                        "blue_squares",
                        "green_triangle_position",
                        "top_text",
                    ],
                    "additionalProperties": False,
                },
            },
        }

        tool_body = {
            "model": self.model,
            "messages": [
                {
                    "role": "user",
                    "content": [
                        {
                            "type": "text",
                            "text": (
                                "观察图片，必须调用 submit_visual_observation。"
                                "数形状、判断绿色三角形位置，并逐字读取顶部英文。"
                            ),
                        },
                        {
                            "type": "image_url",
                            "image_url": {"url": self.uri("image1")},
                        },
                    ],
                }
            ],
            "temperature": 0,
            "max_tokens": 512,
            "chat_template_kwargs": {"enable_thinking": False},
            "tools": [visual_tool],
            "tool_choice": "required",
        }

        def vision_tool_check(data: Any, _: requests.Response):
            calls = data["choices"][0]["message"].get("tool_calls") or []

            if not calls:
                return False, "图片输入后无 tool_calls", {}

            fn = calls[0]["function"]
            args = json.loads(fn.get("arguments") or "{}")

            ok = (
                fn.get("name") == "submit_visual_observation"
                and args.get("red_circles") == 3
                and args.get("blue_squares") == 2
                and norm_pos(args.get("green_triangle_position"))
                == "bottom-right"
                and "AI TEST 2026"
                in str(args.get("top_text", "")).upper()
            )

            return (
                ok,
                "Vision + Tool Calling Ground Truth 匹配"
                if ok
                else f"Vision Tool 异常: {args}",
                {"arguments": args},
            )

        self.request(
            "vision_chat_tool_call",
            "Vision + Agent",
            "POST",
            "/v1/chat/completions",
            tool_body,
            self.oh(),
            vision_tool_check,
        )

        # Responses Vision：当前服务 OpenAPI 要求 detail 必填。
        responses_vision_body = {
            "model": self.model,
            "input": [
                {
                    "role": "user",
                    "content": [
                        {
                            "type": "input_text",
                            "text": self.vision_prompt(),
                        },
                        {
                            "type": "input_image",
                            "detail": "auto",
                            "image_url": self.uri("image1"),
                        },
                    ],
                }
            ],
            "max_output_tokens": 512,
            "reasoning": {"effort": "none"},
        }

        def responses_vision_check(data: Any, _: requests.Response):
            texts = []
            for item in (
                data.get("output", [])
                if isinstance(data, dict)
                else []
            ):
                if item.get("type") == "message":
                    texts.extend(
                        c.get("text") or ""
                        for c in item.get("content", [])
                        if c.get("type") == "output_text"
                    )

            text = "".join(texts)
            obj = parse_json_text(text)
            ok, note, facts = vision_check(obj)
            facts["raw_text"] = text

            return (
                ok,
                "Responses input_image 匹配" if ok else note,
                facts,
            )

        self.request(
            "vision_responses_base64",
            "Vision / Responses",
            "POST",
            "/v1/responses",
            responses_vision_body,
            self.oh(),
            responses_vision_check,
        )

        anthropic_vision_body = {
            "model": self.model,
            "max_tokens": 768,
            "thinking": {"type": "disabled"},
            "messages": [
                {
                    "role": "user",
                    "content": [
                        {
                            "type": "image",
                            "source": {
                                "type": "base64",
                                "media_type": "image/png",
                                "data": self.assets["image1"]["b64"],
                            },
                        },
                        {
                            "type": "text",
                            "text": self.vision_prompt(),
                        },
                    ],
                }
            ],
        }

        def anthropic_vision_check(data: Any, _: requests.Response):
            text = "".join(
                x.get("text") or ""
                for x in (data.get("content") or [])
                if isinstance(x, dict) and x.get("type") == "text"
            )
            obj = parse_json_text(text)
            ok, note, facts = vision_check(obj)
            facts["raw_text"] = text
            return (
                ok,
                "Anthropic image 匹配" if ok else note,
                facts,
            )

        self.request(
            "vision_anthropic_base64",
            "Vision / Anthropic",
            "POST",
            "/v1/messages",
            anthropic_vision_body,
            self.ah(),
            anthropic_vision_check,
        )

        if self.remote_url:
            remote_body = {
                "model": self.model,
                "messages": [
                    {
                        "role": "user",
                        "content": [
                            {
                                "type": "text",
                                "text": "用一句话描述图片。",
                            },
                            {
                                "type": "image_url",
                                "image_url": {"url": self.remote_url},
                            },
                        ],
                    }
                ],
                "max_tokens": 256,
                "chat_template_kwargs": {"enable_thinking": False},
            }

            self.request(
                "vision_remote_url",
                "Vision / Network",
                "POST",
                "/v1/chat/completions",
                remote_body,
                self.oh(),
                lambda d, _: (
                    bool(d["choices"][0]["message"].get("content")),
                    "公网 image_url 可读取",
                    {},
                ),
            )

        else:
            self.skip(
                "vision_remote_url",
                "Vision / Network",
                "/v1/chat/completions",
                (
                    "默认不测公网 URL，避免把出网问题误判为 "
                    "Vision 不支持"
                ),
            )

    # ------------------------------------------------------------------
    # 可选长上下文
    # ------------------------------------------------------------------

    def tokenize_count(self, text: str) -> Optional[int]:
        # 这里也使用统一重试逻辑，但不产生正式测试项。
        max_attempts = 1 + self.retries

        for attempt in range(1, max_attempts + 1):
            try:
                r = self.s.post(
                    self.url("/tokenize"),
                    headers=self.oh(),
                    json={
                        "model": self.model,
                        "prompt": text,
                        "add_special_tokens": False,
                    },
                    timeout=(
                        self.connect_timeout,
                        self.read_timeout,
                    ),
                    verify=self.verify_tls,
                )

                if (
                    r.status_code in RETRYABLE_HTTP_STATUS
                    and attempt < max_attempts
                ):
                    time.sleep(self.backoff_seconds(attempt, r))
                    continue

                if not (200 <= r.status_code < 300):
                    return None

                data = r.json()

                if isinstance(data.get("count"), int):
                    return data["count"]

                return len(data.get("tokens") or [])

            except Exception as exc:
                if (
                    self.should_retry_exception(exc)
                    and attempt < max_attempts
                ):
                    time.sleep(self.backoff_seconds(attempt))
                    continue
                return None

        return None

    def long_context(self) -> None:
        if not self.long_targets:
            return

        long_dir = self.out / "long_context"
        long_dir.mkdir(exist_ok=True)

        unit = (
            "这是长上下文测试固定段落。"
            "The quick brown fox jumps over the lazy dog. "
            "0123456789 ABCDEFGHIJKLMNOPQRSTUVWXYZ。\n"
        )

        for target in self.long_targets:
            if target >= self.context_len:
                self.skip(
                    f"long_context_{target}",
                    "Long Context",
                    "/v1/chat/completions",
                    (
                        "目标达到/超过 max_model_len；"
                        "需为模板和输出预留空间"
                    ),
                )
                continue

            repeats = max(10, target // 25)
            text = unit * repeats
            count = self.tokenize_count(text)

            for _ in range(3):
                if not count:
                    break

                ratio = target / count
                if 0.96 <= ratio <= 1.04:
                    break

                repeats = max(1, int(repeats * ratio))
                text = unit * repeats
                count = self.tokenize_count(text)

            fp = long_dir / f"target_{target}_actual_{count}.txt"
            fp.write_text(text, encoding="utf-8")

            body = {
                "model": self.model,
                "messages": [
                    {
                        "role": "user",
                        "content": text + "\n只回答：LONG_CONTEXT_OK",
                    }
                ],
                "temperature": 0,
                "max_tokens": 32,
                "chat_template_kwargs": {"enable_thinking": False},
            }

            def check(
                data: Any,
                _: requests.Response,
                target=target,
                count=count,
                fp=fp,
            ):
                text_out = (
                    data["choices"][0]["message"].get("content") or ""
                )
                ok = "LONG_CONTEXT_OK" in text_out
                return (
                    ok,
                    f"target={target}, tokenize_count≈{count}",
                    {
                        "target": target,
                        "count": count,
                        "prompt_file": fp.name,
                        "usage": data.get("usage"),
                    },
                )

            self.request(
                f"long_context_{target}",
                "Long Context",
                "POST",
                "/v1/chat/completions",
                body,
                self.oh(),
                check,
            )

            self.delay(self.heavy_cooldown)

    # ------------------------------------------------------------------
    # 汇总
    # ------------------------------------------------------------------

    def status_of(self, name: str) -> Optional[str]:
        row = next((x for x in self.results if x.name == name), None)
        return row.status if row else None

    def group(self, names: list[str]) -> str:
        statuses = [self.status_of(name) for name in names]

        if all(x == "PASS" for x in statuses):
            return "PASS"

        if any(x == "PASS" for x in statuses):
            return "PARTIAL"

        if all(x in {None, "SKIP"} for x in statuses):
            return "NOT_TESTED"

        return "FAIL"

    def matrix(self) -> list[dict[str, str]]:
        rows = [
            (
                "OpenAI Chat Text",
                ["chat_nonstream", "chat_stream"],
                "非流式 + SSE",
            ),
            (
                "OpenAI Chat Thinking",
                ["chat_thinking_off", "chat_thinking_on"],
                "Thinking OFF + ON",
            ),
            (
                "OpenAI Chat Tool Loop",
                ["chat_tool_call", "chat_tool_result_loop"],
                "tool_calls + tool result",
            ),
            (
                "Responses / Codex",
                ["responses_nonstream", "responses_stream"],
                "Responses JSON + SSE",
            ),
            (
                "Responses Tool Loop",
                ["responses_tool_call", "responses_tool_result_loop"],
                "function_call + output",
            ),
            (
                "Anthropic Messages",
                ["anthropic_nonstream", "anthropic_stream"],
                "Message + SSE",
            ),
            (
                "Anthropic Tool Loop",
                ["anthropic_tool_use", "anthropic_tool_result_loop"],
                "tool_use + result",
            ),
            (
                "Vision / OpenAI Chat",
                [
                    "vision_chat_base64",
                    "vision_chat_stream",
                    "vision_multi_image",
                ],
                "单图 + SSE + 多图",
            ),
            (
                "Vision + Tool Calling",
                ["vision_chat_tool_call"],
                "图像 -> 结构化 Tool Call",
            ),
            (
                "Vision / Responses",
                ["vision_responses_base64"],
                "input_image + detail",
            ),
            (
                "Vision / Anthropic",
                ["vision_anthropic_base64"],
                "base64 image block",
            ),
        ]

        if self.long_targets:
            rows.append(
                (
                    "Long Context",
                    [f"long_context_{x}" for x in self.long_targets],
                    f"targets={self.long_targets}",
                )
            )

        return [
            {
                "capability": capability,
                "status": self.group(names),
                "basis": basis,
            }
            for capability, names, basis in rows
        ]

    def finish(self) -> None:
        environment = {
            "generated_at": now_iso(),
            "python": sys.version,
            "platform": platform.platform(),
            "requests_version": requests.__version__,
            "pillow_version": getattr(Image, "__version__", None),
            "script_version": SCRIPT_VERSION,
            "script_sha256": script_sha256(),
            "base_url": self.base,
            "model": self.model,
            "declared_context_length": self.context_len,
            "network_policy": {
                "connect_timeout": self.connect_timeout,
                "read_timeout": self.read_timeout,
                "retries": self.retries,
                "retry_backoff": self.retry_backoff,
                "max_backoff": self.max_backoff,
                "retry_read_timeout": self.retry_read_timeout,
                "retryable_http_status": sorted(RETRYABLE_HTTP_STATUS),
                "inter_test_delay": self.inter_test_delay,
                "heavy_cooldown": self.heavy_cooldown,
            },
            "remote_url_test": bool(self.remote_url),
            "long_context_targets": self.long_targets,
            "assets": {
                k: {
                    x: v[x]
                    for x in ["filename", "bytes", "sha256", "truth"]
                }
                for k, v in self.assets.items()
            },
        }

        (self.out / "environment.json").write_text(
            js(environment),
            encoding="utf-8",
        )

        manifest = {
            "generated_at": now_iso(),
            "script_version": SCRIPT_VERSION,
            "script_sha256": script_sha256(),
            "base_url": self.base,
            "model": self.model,
            "results": [asdict(x) for x in self.results],
            "support_matrix": self.matrix(),
        }

        (self.out / "manifest.json").write_text(
            js(manifest),
            encoding="utf-8",
        )

        recovered_rows = [
            row for row in self.results if row.recovered_by_retry
        ]

        lines = [
            "# Qwen3.6 / vLLM 全面 API、Agent 与 Vision 测试",
            "",
            f"- 脚本版本：`{SCRIPT_VERSION}`",
            f"- SHA256：`{script_sha256()}`",
            f"- 时间：`{now_iso()}`",
            f"- API：`{self.base}`",
            f"- 模型：`{self.model}`",
            f"- 声明 Context：`{self.context_len}`",
            (
                f"- 超时：connect={self.connect_timeout}s, "
                f"read={self.read_timeout}s"
            ),
            (
                f"- 网络重试：额外 {self.retries} 次，"
                f"backoff={self.retry_backoff}s，"
                f"ReadTimeout 自动重试={self.retry_read_timeout}"
            ),
            "",
            "## 能力矩阵",
            "",
            "| 能力 | 结果 | 判定依据 |",
            "|---|---|---|",
        ]

        for row in self.matrix():
            lines.append(
                f"| {row['capability']} | **{row['status']}** | "
                f"{row['basis']} |"
            )

        lines += [
            "",
            "## 逐项测试",
            "",
            (
                "| # | 分类 | 测试 | Endpoint | 结果 | HTTP | "
                "耗时ms | TTFTms | Attempts | Retry恢复 | 说明 |"
            ),
            (
                "|---:|---|---|---|---|---:|---:|---:|"
                "---:|---|---|"
            ),
        ]

        for row in self.results:
            lines.append(
                f"| {row.seq} | {row.category} | {row.name} | "
                f"`{row.endpoint}` | **{row.status}** | "
                f"{'' if row.http_status is None else row.http_status} | "
                f"{'' if row.elapsed_ms is None else row.elapsed_ms} | "
                f"{'' if row.ttft_ms is None else row.ttft_ms} | "
                f"{row.attempts} | "
                f"{'YES' if row.recovered_by_retry else ''} | "
                f"{row.notes.replace('|', '/')} |"
            )

        lines += [
            "",
            "## 网络重试恢复",
            "",
        ]

        if recovered_rows:
            for row in recovered_rows:
                lines.append(
                    f"- `{row.name}`：经过 {row.attempts} 次尝试后恢复。"
                )
        else:
            lines.append("- 本轮没有测试项依靠自动重试恢复。")

        lines += [
            "",
            "## 状态说明",
            "",
            "- PASS：最终请求与断言均通过。",
            "- FAIL：服务器返回了结果，但协议/行为/断言不满足预期。",
            "- ERROR：网络、连接、超时或客户端异常导致请求未正常完成。",
            "- SKIP：脚本按设计未执行，不属于失败。",
            "",
            "## 重试原则",
            "",
            (
                "- 自动重试：连接失败、ConnectTimeout、ChunkedEncodingError、"
                "408/425/429/500/502/503/504。"
            ),
            (
                "- 不自动重试：400/401/403/404/409/422，"
                "因为这类通常是请求/权限/协议本身的问题。"
            ),
            (
                "- ReadTimeout 默认不自动重试。模型推理可能仍在服务端执行，"
                "盲目重试可能进一步占用 NPU。"
            ),
            (
                "- SSE 收到部分内容后中断也不自动重放，"
                "避免把两次输出混成一条结果。"
            ),
            "",
            "## Vision Ground Truth",
            "",
            (
                "- vision_test_1.png：`AI TEST 2026`；"
                "3 红圆；2 蓝方块；绿色三角形右下。"
            ),
            (
                "- vision_test_2.png：`SECOND IMAGE`；"
                "4 紫方块；1 橙色圆。"
            ),
        ]

        (self.out / "summary.md").write_text(
            "\n".join(lines),
            encoding="utf-8",
        )

    # ------------------------------------------------------------------
    # 总流程
    # ------------------------------------------------------------------

    def run(self) -> None:
        print("=" * 104)
        print("Qwen3.6 全面 API + Agent + Vision 测试 v3")
        print("Script   :", SCRIPT_VERSION, "sha256=" + script_sha256()[:12])
        print("Base URL :", self.base)
        print("Model    :", self.model)
        print(
            "Timeout  :",
            f"connect={self.connect_timeout}s read={self.read_timeout}s",
        )
        print(
            "Retry    :",
            f"{self.retries} extra attempts, backoff={self.retry_backoff}s, "
            f"retry_read_timeout={self.retry_read_timeout}",
        )
        print("Output   :", self.out)
        print("=" * 104)

        self.basic()
        self.chat()
        self.responses()
        self.anthropic()
        self.vision()
        self.long_context()
        self.metrics("after")
        self.finish()

        print("=" * 104)
        print("测试完成")
        print("Summary :", self.out / "summary.md")
        print("Manifest:", self.out / "manifest.json")
        print("=" * 104)


def parse_targets(text: str) -> list[int]:
    if not text.strip():
        return []

    values = []
    for part in text.split(","):
        part = part.strip()
        if not part:
            continue

        value = int(part)
        if value <= 0:
            raise ValueError("long context target 必须 > 0")

        values.append(value)

    return values


def main() -> int:
    p = argparse.ArgumentParser(
        description="Qwen3.6 全面 API + Agent + Vision 测试 v3"
    )

    p.add_argument(
        "--base-url",
        default=os.getenv("QWEN_BASE_URL", ""),
        help="API 根地址，例如 http://<INTERNAL_HOST>:<PORT>",
    )
    p.add_argument(
        "--api-key",
        default=os.getenv("QWEN_API_KEY", ""),
        help="API Key；推荐用 QWEN_API_KEY 环境变量",
    )
    p.add_argument(
        "--model",
        default=os.getenv("QWEN_MODEL", DEFAULT_MODEL),
    )
    p.add_argument(
        "--context-len",
        type=int,
        default=int(
            os.getenv("QWEN_CONTEXT_LEN", str(DEFAULT_CONTEXT))
        ),
    )

    p.add_argument(
        "--connect-timeout",
        type=int,
        default=DEFAULT_CONNECT_TIMEOUT,
        help=f"建立连接超时，默认 {DEFAULT_CONNECT_TIMEOUT}s",
    )
    p.add_argument(
        "--read-timeout",
        type=int,
        default=DEFAULT_READ_TIMEOUT,
        help=f"模型响应读取超时，默认 {DEFAULT_READ_TIMEOUT}s",
    )
    # 兼容以前的 --timeout；如设置，则覆盖 read-timeout。
    p.add_argument(
        "--timeout",
        type=int,
        default=None,
        help="兼容旧参数：等价于 --read-timeout",
    )
    p.add_argument(
        "--retries",
        type=int,
        default=DEFAULT_RETRIES,
        help=(
            f"网络/可恢复 HTTP 错误的额外重试次数，"
            f"默认 {DEFAULT_RETRIES}（总尝试次数=1+retries）"
        ),
    )
    p.add_argument(
        "--retry-backoff",
        type=float,
        default=DEFAULT_RETRY_BACKOFF,
        help=f"指数退避起始秒数，默认 {DEFAULT_RETRY_BACKOFF}",
    )
    p.add_argument(
        "--max-backoff",
        type=float,
        default=DEFAULT_MAX_BACKOFF,
        help=f"最大退避秒数，默认 {DEFAULT_MAX_BACKOFF}",
    )
    p.add_argument(
        "--retry-read-timeout",
        action="store_true",
        help=(
            "ReadTimeout 后也自动重试；默认关闭，"
            "因为前一个重推理可能仍在服务端运行"
        ),
    )
    p.add_argument(
        "--inter-test-delay",
        type=float,
        default=DEFAULT_INTER_TEST_DELAY,
        help=f"普通测试间隔，默认 {DEFAULT_INTER_TEST_DELAY}s",
    )
    p.add_argument(
        "--heavy-cooldown",
        type=float,
        default=DEFAULT_HEAVY_COOLDOWN,
        help=f"Thinking 等重测试后的冷却时间，默认 {DEFAULT_HEAVY_COOLDOWN}s",
    )

    p.add_argument(
        "--output",
        default="qwen_api_test_records_v3",
    )
    p.add_argument(
        "--insecure",
        action="store_true",
        help="关闭 TLS 校验；仅用于明确可信的内网自签名环境",
    )
    p.add_argument(
        "--remote-image-url",
        default="",
        help="可选公网图片 URL；默认不测",
    )
    p.add_argument(
        "--long-context-targets",
        default="",
        help="可选，例如 4096,16384,60000；默认不跑长上下文",
    )

    args = p.parse_args()

    if not args.base_url:
        print(
            "请设置 QWEN_BASE_URL 或 --base-url",
            file=sys.stderr,
        )
        return 2

    try:
        long_targets = parse_targets(args.long_context_targets)
    except Exception as exc:
        print(
            f"--long-context-targets 参数错误: {exc}",
            file=sys.stderr,
        )
        return 2

    read_timeout = (
        args.timeout
        if args.timeout is not None
        else args.read_timeout
    )

    run_id = datetime.now().strftime("%Y%m%d_%H%M%S")
    out = Path(args.output) / run_id
    out.mkdir(parents=True, exist_ok=True)

    suite = Suite(
        base=args.base_url,
        key=args.api_key,
        model=args.model,
        out=out,
        connect_timeout=args.connect_timeout,
        read_timeout=read_timeout,
        retries=args.retries,
        retry_backoff=args.retry_backoff,
        max_backoff=args.max_backoff,
        retry_read_timeout=args.retry_read_timeout,
        inter_test_delay=args.inter_test_delay,
        heavy_cooldown=args.heavy_cooldown,
        verify_tls=not args.insecure,
        context_len=args.context_len,
        remote_url=args.remote_image_url,
        long_targets=long_targets,
    )

    suite.run()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())